"""Compose a complete result-reuse workflow through the lightweight CLI.

Input: Parquet generated by `rowtrail-runtime fixtures`, with id/region/amount.
Python is optional for examples; the RowTrail binaries do not depend on it.
"""
import argparse
import json
import subprocess

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source")
parser.add_argument("--workspace", default=".rowtrail")
parser.add_argument("--rowtrail", default="rowtrail")
args = parser.parse_args()


def call(method, params):
    process = subprocess.run(
        [args.rowtrail, "--workspace", args.workspace, "call", method],
        input=json.dumps(params), capture_output=True, text=True, timeout=65,
    )
    response = json.loads(process.stdout)
    if not response["ok"]:
        raise RuntimeError(response["error"])
    return response["result"]


def calculate(bindings, sql):
    result = call("query", {"bindings": bindings, "sql": sql,
                           "execution": {"wait_ms": 1000, "run_timeout_ms": 30000}})
    while result["job"]["state"] in ("queued", "running", "stopping"):
        result = call("control", {"action": "wait", "ref": result["job"]["id"],
                                  "wait_ms": 1000})
    if result["job"]["state"] != "completed":
        raise RuntimeError(result["job"])
    reference = {"result_ref": result["job"]["result_ref"],
                 "revision": result["readable_revision"]}
    return reference, result["job"]["metrics"]


opened = call("open", {"source": args.source})
source = {"dataset_ref": opened["dataset_ref"], "manifest_ref": opened["manifest_ref"]}
saved, materialization = calculate(
    {"original": source},
    "SELECT id, region, amount FROM original WHERE amount IS NOT NULL",
)
grouped, group_metrics = calculate(
    {"saved": saved},
    "SELECT region, SUM(amount) AS total FROM saved GROUP BY region ORDER BY region NULLS LAST",
)
positive, count_metrics = calculate(
    {"saved": saved}, "SELECT COUNT(*) AS positive_rows FROM saved WHERE amount > 0",
)
print(json.dumps({
    "source": source,
    "saved_result": saved,
    "region_totals": call("read", {**grouped, "max_rows": 10}),
    "positive_count": call("read", positive),
    "materialization_io": materialization["io"],
    "branch_io": [group_metrics["io"], count_metrics["io"]],
}, ensure_ascii=False, indent=2))
