"""Compose a complete result-reuse workflow through a persistent native session.

Input: Parquet generated by `rowtrail-runtime fixtures`, with id/region/amount.
Python is optional for examples; the RowTrail binaries do not depend on it.
"""
import argparse
import json
from session_client import RowTrail

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source")
parser.add_argument("--workspace", default=".rowtrail")
parser.add_argument("--rowtrail", default="rowtrail")
args = parser.parse_args()


with RowTrail(args.rowtrail, args.workspace) as client:
    source = client.open(args.source)
    saved = client.query(
        "SELECT id, region, amount FROM original WHERE amount IS NOT NULL",
        {"original": source},
        execution={"output": {"max_rows": 0, "max_bytes": 8192}},
    )
    grouped = client.query(
        "SELECT region, SUM(amount) AS total FROM saved GROUP BY region ORDER BY region NULLS LAST",
        {"saved": saved},
    )
    positive = client.query(
        "SELECT COUNT(*) AS positive_rows FROM saved WHERE amount > 0", {"saved": saved},
    )
    print(json.dumps({
        "source": client.binding(source),
        "saved_result": client.binding(saved),
        "region_totals": client.observe(grouped),
        "positive_count": client.observe(positive),
        "materialization_io": saved["job"]["metrics"]["io"],
        "branch_io": [r["job"]["metrics"]["io"] for r in (grouped, positive)],
    }, ensure_ascii=False, indent=2))
